Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Yoast.YoastSeoForNeos:YoastInfoView:
            resource: 'resource://PunktDe.NeosEnvironmentDisplay/Public/NeosEnvironmentDisplay/Plugin.js'
        stylesheets:
          Yoast.YoastSeoForNeos:YoastInfoView:
            resource: 'resource://PunktDe.NeosEnvironmentDisplay/Public/NeosEnvironmentDisplay/Plugin.css'

      frontendConfiguration:
        'PunktDe.NeosEnvironmentDisplay':
          backgroundColor: '#00adee'
          label: 'Development'
          icon: 'cog'
